sudo: required
language: julia
os:
    - osx
    - linux
julia:
    - 0.3
    - 0.4
    - nightly

notifications:
    email: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - gfortran

matrix:
  allow_failures:
    - os: osx # allow OS X to fail until intermittent failures can be resolved.

script:
  - $CXX --version
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - $CXX --version
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - xvfb-run julia -e 'Pkg.clone(pwd()); Pkg.build("ElasticFDA"); Pkg.test("ElasticFDA"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("ElasticFDA")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
