sudo: required
language: julia
os:
    - osx
    - linux
julia:
    - 0.3
    - 0.4
    - nightly

notifications:
    email: false

addons:
  apt:
    packages:
    - gfortran

matrix:
  allow_failures: 
    - os: osx # allow OS X to fail until intermittent failures can be resolved.

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - xvfb-run julia -e 'Pkg.clone(pwd()); Pkg.build("ElasticFDA"); Pkg.test("ElasticFDA"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("ElasticFDA")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
